version: '3.9'

services:
  web:
    build:
      context: .
      args:
        - BASE_URL=https://dev.guvictory-frontend-hub.ru
    ports:
      # The Nginx config expects port 5173 (for uniformity with dev mode)
      - '5173:3000'
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: 'postgres:15.3-bullseye'
    env_file:
      - ./.env.db
