name: Static code analysis
description: Performs linting with ESLint and svelte-check, checks code style with Prettier 

runs:
  using: 'composite'
  steps:
    - name: ESLint & Prettier
      shell: bash
      run: npm run lint
      
    - name: svelte-check
      shell: bash
      continue-on-error: true
      run: npm run check
